services:
  - type: web
    name: locally-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: GOOGLE_MAPS_API_KEY
        fromSecret: google_maps_api_key
      - key: NODE_ENV
        value: production
